apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: sscglobalinc-com-tls
spec:
  secretName: sscglobalinc-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sscglobalinc.com
  dnsNames:
    - sscglobalinc.com
    - www.sscglobalinc.com
